[pytest]
testpaths = pruebas/tests
pythonpath = pruebas
addopts = --browser chromium --base-url https://web.stremio.com --alluredir=reports/allure-results -n auto
markers = authenticated: tests que requieren sesion autenticada via API

