name: Pruebas E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Crear carpetas necesarias
        run: mkdir -p reports screenshots

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar browsers
        run: playwright install chromium

      - name: Correr pruebas
        env:
          STREMIO_EMAIL: ${{ secrets.STREMIO_EMAIL }}
          STREMIO_PASSWORD: ${{ secrets.STREMIO_PASSWORD }}
        run: pytest

      - name: Instalar Allure CLI
        if: always()
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Generar reporte Allure
        if: always()
        run: allure generate reports/allure-results -o reports/allure-report --clean

      - name: Subir screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/

      - name: Subir reporte como artifact de Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4