name: Pruebas E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, webkit]
    container:
      image: mcr.microsoft.com/playwright/python:v1.58.0-noble
    steps:
      - uses: actions/checkout@v4

      - name: Crear carpetas necesarias
        run: mkdir -p reports screenshots

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Correr pruebas
        env:
          STREMIO_EMAIL: ${{ secrets.STREMIO_EMAIL }}
          STREMIO_PASSWORD: ${{ secrets.STREMIO_PASSWORD }}
          CI: "true"
          HOME: /root
        run: pytest --override-ini="addopts=--browser ${{ matrix.browser }} --base-url https://web.stremio.com --alluredir=reports/allure-results -n auto"

      - name: Subir screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: screenshots/

      - name: Subir resultados Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: reports/allure-results

  report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Descargar todos los resultados Allure
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: reports/allure-results
          merge-multiple: true

      - name: Instalar Allure CLI
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Generar reporte Allure
        run: allure generate reports/allure-results -o reports/allure-report --clean

      - name: Subir reporte como artifact de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure-report

  deploy:
    needs: report
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
